version: '3.8'

services:
  pg-primary:
    image: postgres:14
    container_name: pg-primary
    environment:
      POSTGRES_PASSWORD: rootpass
      POSTGRES_USER: replicator
    volumes:
      - ./pg-primary/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      pgnet:
        ipv4_address: 172.16.0.2

  pg-replica:
    image: postgres:14
    container_name: pg-replica
    environment:
      POSTGRES_PASSWORD: rootpass
      POSTGRES_USER: replicator
    depends_on:
      - pg-primary
    ports:
      - "5433:5432"
    networks:
      pgnet:
        ipv4_address: 172.16.0.3

  keepalived-master:
    image: keepalived-master
    container_name: keepalived-master
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    networks:
      pgnet:
        ipv4_address: 172.16.0.4

  keepalived-backup:
    image: keepalived-backup
    container_name: keepalived-backup
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    networks:
      pgnet:
        ipv4_address: 172.16.0.5

networks:
  pgnet:
    external: true

